import{S as d,i}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();const u="41511602-ac1f0d864a13fd01c911f294b",m=document.querySelector(".search-form"),c=document.querySelector(".gallery"),f=document.querySelector(".search-input"),p=new d(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".loader");l.style.display="none";m.addEventListener("submit",h);function h(t){t.preventDefault();const r=f.value.trim();if(!r){i.warning({title:"Warning!",message:"Please enter image name!",position:"topRight"});return}b(),l.style.display="block";const a=new URLSearchParams({key:u,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${a}`).then(o=>{if(l.style.display="none",!o.ok)throw new Error(o.status);return o.json()}).then(o=>{if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits),p.refresh()}).catch(o=>{console.error("Error fetching images:",o),i.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})})}function y(t){t.forEach(r=>{const a=g(r);c.appendChild(a)})}function g(t){const r=document.createElement("div");return r.classList.add("card"),r.innerHTML=`
    <a class="gallery-link" href="${t.largeImageURL}">
        <img class="card-image" src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
      </a>
      <div class="card-info">
        <p class="card-text"><b>Likes:</b> ${t.likes}</p>
        <p class="card-text"><b>Views:</b> ${t.views}</p>
        <p class="card-text"><b>Comments:</b> ${t.comments}</p>
        <p class="card-text"><b>Downloads:</b> ${t.downloads}</p>
      </div>
    `,r}function b(){c.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
